from __future__ import annotations

import autopost_news as app
import main as news
from ai_cover import generate_cover
from news_sources import fetch_stories_resilient

# Use several news sources instead of relying on Google News alone.
news.fetch_stories = fetch_stories_resilient


def ai_only_image(story: news.Story) -> dict:
    """Marker object used by the existing publishing pipeline.

    The actual picture is generated by the image model in ai_cover.generate_cover.
    There is intentionally no Wikimedia/stock fallback: if AI generation fails,
    publication stops instead of sending a template/stock image.
    """
    return {
        "url": "ai-generated",
        "page": "ai-generated",
        "license": "AI-generated",
        "credit": "",
    }


def ai_build_cover(story: news.Story, image_meta: dict) -> object:
    return generate_cover(story, image_meta)


app.commons_image = ai_only_image
app.build_cover = ai_build_cover


if __name__ == "__main__":
    app.main()
